version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: "minio"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=exampleroot
      - MINIO_ROOT_PASSWORD=examplepass
    ports:
      - 9000:9000
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
